// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package providers

import (
	"wirepoc/internal/controllers"
)

// Injectors from wire.go:

func InitializeMessages(greetingMessage controllers.GreetingMessage, farewellMessage controllers.FarewellMessage) (controllers.IMessages, error) {
	iMessages := controllers.NewMessageController(greetingMessage, farewellMessage)
	return iMessages, nil
}
